### ISSUE TITLE
set up dev environment

### ISSUE THREAD

**Issue by gubuntu** [kartoza/miniSASS#1]
Please clone this fork and set up a local dev environment. The docs are hopefully self-explanatory - where they are deficient please expand them

It's basically a Django-CMS site with GeoDjango brought in as a plugin. 

You don't need the whole mapping infrastructure locally but will need the Django DB content as well as a few tables that are managed via the web app (sites and observations). I'll probably set up a btsync share for these. 

Spend a day or so setting it up, getting familiar with the code (doing a bit of a review at the same time). Once you've got it going, I'll be assigning some of the issues at https://github.com/sokolic/miniSASS/issues to you. 

Push into this repo after testing, then do PRs against https://github.com/sokolic/miniSASS.

I would like to use git flow. Please coordinate this as well as the featur / release policy from Frank Sokolic, the project lead.

Ideally discussions to take place in minisass HipChat room.

**Comment by ismailsunni** [comment]
Closing this, since I have a working dev environment now.
